version: '3.7'

services:
  iris:
    init: true
    hostname: iris
    build:
      context: .
      dockerfile: Dockerfile
    image: workshop-iris-datalake:iris
    container_name: iris
    ports:
    - "52773:52773"
    - "1972:1972"
    volumes:
    - .:/app

networks:
  datapipe-network:
    name: datapipe-network