version: '3.7'

services:

  iris:
    init: true
    hostname: iris
    build:
      context: .
      dockerfile: Dockerfile
    image: workshop-smart-data-fabric:iris
    container_name: iris
    ports:
    - "52773:52773"
    - "1972:1972"
    volumes:
    - .:/app

  webserver:
    hostname: webserver
    build:
      context: webserver
      dockerfile: Dockerfile
    image: workshop-smart-data-fabric:webserver
    container_name: webserver
    init: true
    depends_on:
      - iris
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./webserver:/webserver
    environment:
    - ISC_DATA_DIRECTORY=/webserver

  jupyter:
    container_name: jupyter
    build:
      context: jupyter
    ports: 
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes: 
      - ./jupyter/notebooks:/home/jovyan/
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"  

networks:
  datapipe-network:
    name: datapipe-network